project:
  type: website

website:
  title: "Analytics for Accounting Data"
  reader-mode: true
  page-footer: "Copyright 2024@Sharif Islam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true



