project:
  type: website

website:
  title: "Analytics for Accounting Data"
  reader-mode: false
  page-navigation: true
  page-footer: 
    background: dark
    center: 
      - "Copyright@2024, Sharif Islam"
  navbar:
    logo: images/siuc1.jpeg
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: syllabus.qmd
        text: Syllabus
      - href: books.qmd
        text: Books
      - href: projects.qmd
        text: Projects
      - href: readings.qmd
        text: Readings
      - href: recent-developments.qmd
        text: News
  sidebar: 
    style: docked
    search: true
    alignment: left
    contents: 
      - section: "Week 01"
        contents: week01.qmd
      - section: "Week 02"
        contents: week02.qmd 
    
format:
  html:
    theme: superhero
    toc: true
    mainfont: serif
    embed-resources: true
css: styles.css



