project:
  type: website

website:
  title: "Analytics for Accounting Data"
  reader-mode: false
  page-footer: "Copyright 2024@Sharif Islam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - syllabus.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    mainfont: serif
    embed-resources: true



