project:
  type: website

website:
  title: "Analytics for Accounting Data"
  reader-mode: false
  page-footer: 
    background: dark
    center: 
      - "Copyright@2024, Sharif Islam"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: syllabus.qmd
        text: Syllabus
      - href: books.qmd
        text: Books
      - href: projects.qmd
        text: Projects
      - href: readings.qmd
        text: Readings
      - href: recent-developments.qmd
        text: News

format:
  html:
    theme: united
    toc: true
    mainfont: serif
    embed-resources: true
css: styles.css



