project:
  type: website

website:
  title: "Analytics for Accounting Data"
  reader-mode: false
  page-footer: 
    background: dark
    center: 
      - "Copyright@2024, Sharif Islam"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - syllabus.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    mainfont: serif
    embed-resources: true



